-- M-profile Lab member center full deployment SQL
-- Generated by scripts/prepare-member-deployment.mjs
-- Execute in Supabase SQL Editor with an owner/service role.
--
-- Review the first result set from member_center_predeploy_check.sql.
-- If any row has ok=false, stop and fix it before relying on the later results.
-- The member_center_deployment_check.sql result set must have ok=true for every row.
-- database/member_center_e2e_check.sql is intentionally not bundled here because it writes temporary test data.
-- Run database/member_center_e2e_check.sql separately after deployment if you want a database-side smoke test.


-- ============================================================================
-- 1. database/member_center_predeploy_check.sql
-- sha256: a4812c072df1e090ddbb63408e773c343fe049e00138274e228dcf0819d974a6
-- ============================================================================

-- Member center pre-deployment check
-- Run before create_member_center_tables.sql.
-- This script only creates a temporary result table in the current SQL session.

CREATE TEMP TABLE IF NOT EXISTS member_center_predeploy_results (
  check_type TEXT NOT NULL,
  name TEXT NOT NULL,
  ok BOOLEAN NOT NULL,
  detail TEXT NOT NULL
);

TRUNCATE member_center_predeploy_results;

DO $$
DECLARE
  relation_name TEXT;
  duplicate_count INTEGER;
  detail_text TEXT;
BEGIN
  FOREACH relation_name IN ARRAY ARRAY['users', 'test_records', 'test_results', 'messages', 'admins']
  LOOP
    INSERT INTO member_center_predeploy_results (check_type, name, ok, detail)
    VALUES (
      'required_base_table',
      relation_name,
      to_regclass('public.' || relation_name) IS NOT NULL,
      CASE
        WHEN to_regclass('public.' || relation_name) IS NOT NULL THEN 'found'
        ELSE 'missing: deploy the existing base schema before member center SQL'
      END
    );
  END LOOP;

  INSERT INTO member_center_predeploy_results (check_type, name, ok, detail)
  VALUES (
    'optional_base_table',
    'message_replies',
    true,
    CASE
      WHEN to_regclass('public.message_replies') IS NULL THEN 'missing: create_admin_member_session.sql will not create this table; deploy message replies schema first if留言回复 is used'
      WHEN EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'message_replies'
          AND column_name = 'is_admin'
      ) THEN 'found with is_admin column'
      ELSE 'found; create_admin_member_session.sql will add is_admin column'
    END
  );

  INSERT INTO member_center_predeploy_results (check_type, name, ok, detail)
  VALUES (
    'extension',
    'pgcrypto_available',
    EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'pgcrypto'),
    CASE
      WHEN EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'pgcrypto') THEN 'available'
      ELSE 'missing: pgcrypto is required for crypt(), gen_salt(), gen_random_bytes()'
    END
  );

  IF to_regclass('public.member_subscriptions') IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'member_subscriptions'
        AND column_name IN ('provider', 'provider_ref')
      GROUP BY table_name
      HAVING count(*) = 2
    )
  THEN
    EXECUTE $sql$
      SELECT count(*), COALESCE(string_agg(provider || ':' || provider_ref || ' x' || duplicate_total, ', '), 'none')
      FROM (
        SELECT provider, provider_ref, count(*) AS duplicate_total
        FROM member_subscriptions
        WHERE provider_ref IS NOT NULL
        GROUP BY provider, provider_ref
        HAVING count(*) > 1
        ORDER BY duplicate_total DESC, provider, provider_ref
        LIMIT 10
      ) duplicates
    $sql$ INTO duplicate_count, detail_text;

    INSERT INTO member_center_predeploy_results (check_type, name, ok, detail)
    VALUES (
      'duplicate_guard',
      'member_subscriptions_provider_ref_unique',
      duplicate_count = 0,
      CASE
        WHEN duplicate_count = 0 THEN 'no duplicates'
        ELSE 'duplicates must be merged before creating idx_member_subscriptions_provider_ref_unique: ' || detail_text
      END
    );
  ELSE
    INSERT INTO member_center_predeploy_results (check_type, name, ok, detail)
    VALUES (
      'duplicate_guard',
      'member_subscriptions_provider_ref_unique',
      true,
      'member_subscriptions table or provider/provider_ref columns not present yet'
    );
  END IF;

  IF to_regclass('public.member_orders') IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'member_orders'
        AND column_name IN ('provider', 'provider_ref')
      GROUP BY table_name
      HAVING count(*) = 2
    )
  THEN
    EXECUTE $sql$
      SELECT count(*), COALESCE(string_agg(provider || ':' || provider_ref || ' x' || duplicate_total, ', '), 'none')
      FROM (
        SELECT provider, provider_ref, count(*) AS duplicate_total
        FROM member_orders
        WHERE provider_ref IS NOT NULL
        GROUP BY provider, provider_ref
        HAVING count(*) > 1
        ORDER BY duplicate_total DESC, provider, provider_ref
        LIMIT 10
      ) duplicates
    $sql$ INTO duplicate_count, detail_text;

    INSERT INTO member_center_predeploy_results (check_type, name, ok, detail)
    VALUES (
      'duplicate_guard',
      'member_orders_provider_ref_unique',
      duplicate_count = 0,
      CASE
        WHEN duplicate_count = 0 THEN 'no duplicates'
        ELSE 'duplicates must be merged before creating idx_member_orders_provider_ref_unique: ' || detail_text
      END
    );
  ELSE
    INSERT INTO member_center_predeploy_results (check_type, name, ok, detail)
    VALUES (
      'duplicate_guard',
      'member_orders_provider_ref_unique',
      true,
      'member_orders table or provider/provider_ref columns not present yet'
    );
  END IF;

  IF to_regclass('public.member_share_links') IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'member_share_links'
        AND column_name = 'share_token'
    )
  THEN
    EXECUTE $sql$
      SELECT count(*), COALESCE(string_agg(share_token || ' x' || duplicate_total, ', '), 'none')
      FROM (
        SELECT share_token, count(*) AS duplicate_total
        FROM member_share_links
        WHERE share_token IS NOT NULL
        GROUP BY share_token
        HAVING count(*) > 1
        ORDER BY duplicate_total DESC, share_token
        LIMIT 10
      ) duplicates
    $sql$ INTO duplicate_count, detail_text;

    INSERT INTO member_center_predeploy_results (check_type, name, ok, detail)
    VALUES (
      'duplicate_guard',
      'member_share_links_share_token_unique',
      duplicate_count = 0,
      CASE
        WHEN duplicate_count = 0 THEN 'no duplicates'
        ELSE 'duplicate share_token values must be fixed before deployment: ' || detail_text
      END
    );
  ELSE
    INSERT INTO member_center_predeploy_results (check_type, name, ok, detail)
    VALUES (
      'duplicate_guard',
      'member_share_links_share_token_unique',
      true,
      'member_share_links table or share_token column not present yet'
    );
  END IF;
END;
$$;

SELECT check_type, name, ok, detail
FROM member_center_predeploy_results
ORDER BY check_type, name;


-- ============================================================================
-- 2. database/create_member_center_tables.sql
-- sha256: c1fd350f8350e6fe1e2c0de20eb4b27212f7f5420aae86a67be14c426834e9dc
-- ============================================================================

-- M-profile Lab member center tables
-- Run in Supabase SQL Editor with an owner/service role.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS member_profiles (
  account_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  legacy_user_id_text TEXT REFERENCES users(id) ON DELETE SET NULL,
  display_name TEXT NOT NULL DEFAULT '匿名用户',
  qq TEXT,
  wechat TEXT,
  contact_email TEXT,
  phone TEXT,
  membership_tier TEXT NOT NULL DEFAULT 'free' CHECK (membership_tier IN ('free', 'basic', 'premium', 'lifetime')),
  privacy_settings JSONB NOT NULL DEFAULT '{"hideUserId": true, "hideSensitiveItems": true, "allowPrivateShare": true}'::jsonb,
  notification_settings JSONB NOT NULL DEFAULT '{"monthlySummary": true, "trendReminder": false}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE member_profiles ADD COLUMN IF NOT EXISTS qq TEXT;
ALTER TABLE member_profiles ADD COLUMN IF NOT EXISTS wechat TEXT;
ALTER TABLE member_profiles ADD COLUMN IF NOT EXISTS contact_email TEXT;
ALTER TABLE member_profiles ADD COLUMN IF NOT EXISTS phone TEXT;

CREATE TABLE IF NOT EXISTS member_login_names (
  username TEXT PRIMARY KEY CHECK (username ~ '^[a-z0-9_]{3,24}$'),
  auth_email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS member_subscriptions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plan_code TEXT NOT NULL CHECK (plan_code IN ('free', 'basic_monthly', 'premium_monthly', 'lifetime')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'trialing', 'past_due', 'canceled', 'expired')),
  provider TEXT NOT NULL DEFAULT 'manual',
  provider_ref TEXT,
  starts_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  ends_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS member_orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  legacy_user_id_text TEXT REFERENCES users(id) ON DELETE SET NULL,
  plan_code TEXT NOT NULL CHECK (plan_code IN ('basic_monthly', 'premium_monthly', 'lifetime')),
  amount_cents INTEGER NOT NULL DEFAULT 0 CHECK (amount_cents >= 0),
  currency TEXT NOT NULL DEFAULT 'CNY',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'approved', 'rejected', 'canceled', 'refunded')),
  provider TEXT NOT NULL DEFAULT 'manual',
  provider_ref TEXT,
  contact_email TEXT,
  contact_note TEXT,
  admin_note TEXT,
  requested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  paid_at TIMESTAMP WITH TIME ZONE,
  reviewed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS member_account_events (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  legacy_user_id_text TEXT REFERENCES users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  event_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS member_identity_links (
  account_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  legacy_user_id_text TEXT NOT NULL,
  display_label TEXT,
  first_seen_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (account_id, legacy_user_id_text)
);

CREATE TABLE IF NOT EXISTS member_identity_claims (
  legacy_user_id_text TEXT PRIMARY KEY,
  claim_secret_hash TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS member_devices (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  legacy_user_id_text TEXT REFERENCES users(id) ON DELETE SET NULL,
  device_label TEXT NOT NULL DEFAULT '当前设备',
  user_agent_hash TEXT,
  last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(account_id, legacy_user_id_text, device_label)
);

CREATE TABLE IF NOT EXISTS member_report_unlocks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  legacy_user_id_text TEXT REFERENCES users(id) ON DELETE SET NULL,
  record_id UUID REFERENCES test_records(id) ON DELETE CASCADE,
  unlock_type TEXT NOT NULL DEFAULT 'advanced_report' CHECK (unlock_type IN ('advanced_report', 'comparison_report', 'export_template')),
  source TEXT NOT NULL DEFAULT 'membership',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(account_id, record_id, unlock_type)
);

CREATE TABLE IF NOT EXISTS member_share_links (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  share_token TEXT NOT NULL UNIQUE,
  account_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  legacy_user_id_text TEXT REFERENCES users(id) ON DELETE SET NULL,
  record_id UUID REFERENCES test_records(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '我的测评报告',
  access_code_hash TEXT,
  hidden_sections JSONB NOT NULL DEFAULT '[]'::jsonb,
  expires_at TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  view_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

DROP INDEX IF EXISTS idx_member_subscriptions_user;
CREATE INDEX IF NOT EXISTS idx_member_subscriptions_account ON member_subscriptions(account_id);
CREATE INDEX IF NOT EXISTS idx_member_subscriptions_status ON member_subscriptions(status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_member_subscriptions_provider_ref_unique
  ON member_subscriptions(provider, provider_ref)
  WHERE provider_ref IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_member_orders_account ON member_orders(account_id);
CREATE INDEX IF NOT EXISTS idx_member_orders_status ON member_orders(status);
CREATE INDEX IF NOT EXISTS idx_member_orders_created_at ON member_orders(created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_member_orders_provider_ref_unique
  ON member_orders(provider, provider_ref)
  WHERE provider_ref IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_member_account_events_account ON member_account_events(account_id);
CREATE INDEX IF NOT EXISTS idx_member_account_events_type ON member_account_events(event_type);
CREATE INDEX IF NOT EXISTS idx_member_identity_links_account ON member_identity_links(account_id);
CREATE INDEX IF NOT EXISTS idx_member_identity_links_legacy ON member_identity_links(legacy_user_id_text);
CREATE INDEX IF NOT EXISTS idx_member_identity_claims_updated_at ON member_identity_claims(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_member_login_names_email ON member_login_names(auth_email);
CREATE INDEX IF NOT EXISTS idx_member_devices_account ON member_devices(account_id);
DROP INDEX IF EXISTS idx_member_report_unlocks_user;
CREATE INDEX IF NOT EXISTS idx_member_report_unlocks_account ON member_report_unlocks(account_id);
CREATE INDEX IF NOT EXISTS idx_member_report_unlocks_record ON member_report_unlocks(record_id);
DROP INDEX IF EXISTS idx_member_share_links_user;
CREATE INDEX IF NOT EXISTS idx_member_share_links_account ON member_share_links(account_id);
CREATE INDEX IF NOT EXISTS idx_member_share_links_token ON member_share_links(share_token);
CREATE INDEX IF NOT EXISTS idx_member_share_links_active ON member_share_links(is_active);

CREATE OR REPLACE FUNCTION update_member_center_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_member_profiles_updated_at ON member_profiles;
CREATE TRIGGER update_member_profiles_updated_at
  BEFORE UPDATE ON member_profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_member_center_timestamp();

DROP TRIGGER IF EXISTS update_member_subscriptions_updated_at ON member_subscriptions;
CREATE TRIGGER update_member_subscriptions_updated_at
  BEFORE UPDATE ON member_subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION update_member_center_timestamp();

DROP TRIGGER IF EXISTS update_member_orders_updated_at ON member_orders;
CREATE TRIGGER update_member_orders_updated_at
  BEFORE UPDATE ON member_orders
  FOR EACH ROW
  EXECUTE FUNCTION update_member_center_timestamp();

DROP TRIGGER IF EXISTS update_member_share_links_updated_at ON member_share_links;
CREATE TRIGGER update_member_share_links_updated_at
  BEFORE UPDATE ON member_share_links
  FOR EACH ROW
  EXECUTE FUNCTION update_member_center_timestamp();

CREATE OR REPLACE FUNCTION normalize_member_auth_user_metadata()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  metadata JSONB := COALESCE(NEW.raw_user_meta_data, '{}'::jsonb);
  clean_email TEXT := lower(trim(COALESCE(NEW.email, metadata->>'email', '')));
  fallback_name TEXT;
  fallback_username TEXT;
BEGIN
  fallback_name := COALESCE(
    NULLIF(trim(metadata->>'displayName'), ''),
    NULLIF(trim(metadata->>'display_name'), ''),
    NULLIF(trim(metadata->>'name'), ''),
    NULLIF(trim(metadata->>'nickname'), ''),
    NULLIF(trim(metadata->>'fullName'), ''),
    NULLIF(trim(metadata->>'full_name'), ''),
    NULLIF(split_part(clean_email, '@', 1), ''),
    '会员用户'
  );

  fallback_username := lower(COALESCE(
    NULLIF(trim(metadata->>'username'), ''),
    NULLIF(trim(metadata->>'userName'), ''),
    NULLIF(trim(metadata->>'user_name'), ''),
    NULLIF(trim(metadata->>'loginName'), ''),
    NULLIF(trim(metadata->>'login_name'), ''),
    regexp_replace(split_part(clean_email, '@', 1), '[^A-Za-z0-9_]', '', 'g'),
    'member'
  ));
  fallback_username := left(regexp_replace(fallback_username, '[^a-z0-9_]', '', 'g'), 24);
  IF length(fallback_username) < 3 THEN
    fallback_username := 'member';
  END IF;

  NEW.raw_user_meta_data := metadata || jsonb_build_object(
    'username', fallback_username,
    'userName', fallback_username,
    'user_name', fallback_username,
    'loginName', fallback_username,
    'login_name', fallback_username,
    'displayName', fallback_name,
    'display_name', fallback_name,
    'name', fallback_name,
    'nickname', fallback_name,
    'fullName', fallback_name,
    'full_name', fallback_name,
    'email', clean_email,
    'contactEmail', clean_email,
    'contact_email', clean_email
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS aaa_member_auth_user_metadata_before_write ON auth.users;
CREATE TRIGGER aaa_member_auth_user_metadata_before_write
  BEFORE INSERT OR UPDATE OF email, raw_user_meta_data ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION normalize_member_auth_user_metadata();

CREATE OR REPLACE FUNCTION create_user_settings(p_user_id UUID, p_display_name TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  clean_display_name TEXT := COALESCE(NULLIF(trim(p_display_name), ''), '会员用户');
BEGIN
  IF to_regclass('public.user_settings') IS NULL THEN
    RETURN;
  END IF;

  INSERT INTO public.user_settings (
    user_id,
    display_name,
    theme,
    privacy_level,
    created_at,
    updated_at
  )
  VALUES (
    p_user_id,
    clean_display_name,
    'light',
    'private',
    timezone('utc'::text, now()),
    timezone('utc'::text, now())
  )
  ON CONFLICT DO NOTHING;
END;
$$;

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  metadata JSONB := COALESCE(NEW.raw_user_meta_data, '{}'::jsonb);
  clean_email TEXT := lower(trim(COALESCE(NEW.email, metadata->>'email', '')));
  fallback_name TEXT;
BEGIN
  fallback_name := COALESCE(
    NULLIF(trim(metadata->>'displayName'), ''),
    NULLIF(trim(metadata->>'display_name'), ''),
    NULLIF(trim(metadata->>'name'), ''),
    NULLIF(trim(metadata->>'nickname'), ''),
    NULLIF(trim(metadata->>'fullName'), ''),
    NULLIF(trim(metadata->>'full_name'), ''),
    NULLIF(trim(metadata->>'username'), ''),
    NULLIF(trim(metadata->>'userName'), ''),
    NULLIF(trim(metadata->>'user_name'), ''),
    NULLIF(trim(metadata->>'loginName'), ''),
    NULLIF(trim(metadata->>'login_name'), ''),
    NULLIF(split_part(clean_email, '@', 1), ''),
    '会员用户'
  );

  PERFORM create_user_settings(NEW.id, fallback_name);
  RETURN NEW;
END;
$$;

ALTER TABLE member_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_account_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_identity_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_identity_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_login_names ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_report_unlocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_share_links ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "member_profiles_owner_read" ON member_profiles;
CREATE POLICY "member_profiles_owner_read" ON member_profiles FOR SELECT TO authenticated USING (account_id = auth.uid());

DROP POLICY IF EXISTS "member_profiles_owner_insert" ON member_profiles;

DROP POLICY IF EXISTS "member_profiles_owner_update" ON member_profiles;

DROP POLICY IF EXISTS "member_subscriptions_owner_read" ON member_subscriptions;
CREATE POLICY "member_subscriptions_owner_read" ON member_subscriptions FOR SELECT TO authenticated USING (account_id = auth.uid());

DROP POLICY IF EXISTS "member_orders_owner_read" ON member_orders;
CREATE POLICY "member_orders_owner_read" ON member_orders FOR SELECT TO authenticated USING (account_id = auth.uid());

DROP POLICY IF EXISTS "member_orders_owner_insert" ON member_orders;

DROP POLICY IF EXISTS "member_account_events_owner_read" ON member_account_events;
CREATE POLICY "member_account_events_owner_read" ON member_account_events FOR SELECT TO authenticated USING (account_id = auth.uid());

DROP POLICY IF EXISTS "member_account_events_owner_insert" ON member_account_events;

DROP POLICY IF EXISTS "member_identity_links_owner_read" ON member_identity_links;
CREATE POLICY "member_identity_links_owner_read" ON member_identity_links FOR SELECT TO authenticated USING (account_id = auth.uid());

DROP POLICY IF EXISTS "member_identity_links_owner_insert" ON member_identity_links;

DROP POLICY IF EXISTS "member_identity_links_owner_update" ON member_identity_links;

DROP POLICY IF EXISTS "member_identity_links_owner_delete" ON member_identity_links;

DROP POLICY IF EXISTS "member_identity_claims_no_read" ON member_identity_claims;

DROP POLICY IF EXISTS "member_identity_claims_no_insert" ON member_identity_claims;

DROP POLICY IF EXISTS "member_identity_claims_no_update" ON member_identity_claims;

DROP POLICY IF EXISTS "member_identity_claims_no_delete" ON member_identity_claims;

DROP POLICY IF EXISTS "member_devices_owner_read" ON member_devices;
CREATE POLICY "member_devices_owner_read" ON member_devices FOR SELECT TO authenticated USING (account_id = auth.uid());

DROP POLICY IF EXISTS "member_devices_owner_insert" ON member_devices;

DROP POLICY IF EXISTS "member_devices_owner_update" ON member_devices;

DROP POLICY IF EXISTS "member_report_unlocks_owner_read" ON member_report_unlocks;
CREATE POLICY "member_report_unlocks_owner_read" ON member_report_unlocks FOR SELECT TO authenticated USING (account_id = auth.uid());

DROP POLICY IF EXISTS "member_report_unlocks_owner_insert" ON member_report_unlocks;

DROP POLICY IF EXISTS "member_share_links_owner_read" ON member_share_links;

DROP POLICY IF EXISTS "member_share_links_owner_insert" ON member_share_links;

DROP POLICY IF EXISTS "member_share_links_owner_update" ON member_share_links;

DROP POLICY IF EXISTS "member_share_links_public_read_active" ON member_share_links;

REVOKE INSERT, UPDATE ON member_profiles FROM anon, authenticated;
REVOKE INSERT ON member_orders FROM anon, authenticated;
REVOKE INSERT ON member_report_unlocks FROM anon, authenticated;
REVOKE INSERT ON member_account_events FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON member_identity_links FROM anon, authenticated;
REVOKE SELECT, INSERT, UPDATE, DELETE ON member_identity_claims FROM anon, authenticated;
REVOKE SELECT, INSERT, UPDATE, DELETE ON member_login_names FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON member_devices FROM anon, authenticated;
REVOKE SELECT, INSERT, UPDATE, DELETE ON member_share_links FROM anon, authenticated;
REVOKE SELECT (access_code_hash) ON member_share_links FROM anon, authenticated;

CREATE OR REPLACE FUNCTION normalize_member_privacy_settings(input_settings JSONB)
RETURNS JSONB
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
  RETURN jsonb_build_object(
    'hideUserId', COALESCE((input_settings->>'hideUserId')::BOOLEAN, true),
    'hideSensitiveItems', COALESCE((input_settings->>'hideSensitiveItems')::BOOLEAN, true),
    'allowPrivateShare', COALESCE((input_settings->>'allowPrivateShare')::BOOLEAN, true)
  );
END;
$$;

CREATE OR REPLACE FUNCTION normalize_member_notification_settings(input_settings JSONB)
RETURNS JSONB
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
  RETURN jsonb_build_object(
    'monthlySummary', COALESCE((input_settings->>'monthlySummary')::BOOLEAN, true),
    'trendReminder', COALESCE((input_settings->>'trendReminder')::BOOLEAN, false)
  );
END;
$$;

CREATE OR REPLACE FUNCTION normalize_member_username(input_username TEXT)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  clean_username TEXT := lower(trim(COALESCE(input_username, '')));
BEGIN
  IF clean_username !~ '^[a-z0-9_]{3,24}$' THEN
    RAISE EXCEPTION '用户名只能使用 3-24 位小写字母、数字或下划线';
  END IF;
  RETURN clean_username;
END;
$$;

CREATE OR REPLACE FUNCTION reserve_member_login_name(input_username TEXT, input_auth_email TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  clean_username TEXT := normalize_member_username(input_username);
  clean_email TEXT := lower(trim(COALESCE(input_auth_email, '')));
BEGIN
  IF clean_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' THEN
    RAISE EXCEPTION '请输入有效邮箱';
  END IF;

  IF EXISTS (
    SELECT 1 FROM member_login_names
    WHERE username = clean_username AND auth_email <> clean_email
  ) THEN
    RAISE EXCEPTION '用户名已被占用';
  END IF;

  IF EXISTS (
    SELECT 1 FROM member_login_names
    WHERE auth_email = clean_email AND username <> clean_username
  ) THEN
    RAISE EXCEPTION '邮箱已被注册';
  END IF;

  INSERT INTO member_login_names (username, auth_email, created_at, updated_at)
  VALUES (clean_username, clean_email, timezone('utc'::text, now()), timezone('utc'::text, now()))
  ON CONFLICT (username) DO UPDATE
  SET auth_email = excluded.auth_email,
      updated_at = timezone('utc'::text, now());

  IF NOT EXISTS (
    SELECT 1 FROM member_login_names
    WHERE username = clean_username AND auth_email = clean_email
  ) THEN
    RAISE EXCEPTION '用户名已被占用';
  END IF;

  RETURN jsonb_build_object('username', clean_username);
END;
$$;

CREATE OR REPLACE FUNCTION get_member_login_email(input_username TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  clean_username TEXT := normalize_member_username(input_username);
  found_email TEXT;
BEGIN
  SELECT auth_email INTO found_email
  FROM member_login_names
  WHERE username = clean_username
  LIMIT 1;

  IF found_email IS NULL THEN
    RAISE EXCEPTION '用户名或密码不正确';
  END IF;

  RETURN found_email;
END;
$$;

DROP FUNCTION IF EXISTS link_member_identity(TEXT, TEXT);
DROP FUNCTION IF EXISTS get_or_create_member_profile(TEXT, TEXT);
DROP FUNCTION IF EXISTS register_member_device(TEXT, TEXT, TEXT);

CREATE OR REPLACE FUNCTION link_member_identity(
  input_legacy_user_id_text TEXT,
  input_claim_secret TEXT,
  input_display_label TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
  clean_legacy_id TEXT := NULLIF(trim(input_legacy_user_id_text), '');
  clean_claim_secret TEXT := NULLIF(input_claim_secret, '');
  clean_label TEXT := NULLIF(left(trim(COALESCE(input_display_label, '当前身份')), 80), '');
  linked_row member_identity_links%ROWTYPE;
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录会员账号';
  END IF;

  IF clean_legacy_id IS NULL THEN
    RAISE EXCEPTION '匿名身份不能为空';
  END IF;

  IF clean_claim_secret IS NULL THEN
    RAISE EXCEPTION '匿名身份密钥不能为空';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM member_identity_claims
    WHERE legacy_user_id_text = clean_legacy_id
      AND claim_secret_hash = encode(digest(clean_claim_secret, 'sha256'), 'hex')
  ) THEN
    RAISE EXCEPTION '匿名身份密钥不匹配，无法绑定该测评身份';
  END IF;

  INSERT INTO member_identity_links (
    account_id,
    legacy_user_id_text,
    display_label,
    first_seen_at,
    last_seen_at
  )
  VALUES (
    current_account,
    clean_legacy_id,
    clean_label,
    timezone('utc'::text, now()),
    timezone('utc'::text, now())
  )
  ON CONFLICT (account_id, legacy_user_id_text) DO UPDATE
  SET display_label = COALESCE(excluded.display_label, member_identity_links.display_label),
      last_seen_at = timezone('utc'::text, now())
  RETURNING * INTO linked_row;

  RETURN to_jsonb(linked_row);
END;
$$;

CREATE OR REPLACE FUNCTION register_legacy_identity_claim(
  input_legacy_user_id_text TEXT,
  input_claim_secret TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  clean_legacy_id TEXT := NULLIF(trim(input_legacy_user_id_text), '');
  clean_claim_secret TEXT := NULLIF(input_claim_secret, '');
  inserted_claim member_identity_claims%ROWTYPE;
BEGIN
  IF clean_legacy_id IS NULL THEN
    RAISE EXCEPTION '匿名身份不能为空';
  END IF;

  IF clean_claim_secret IS NULL OR length(clean_claim_secret) < 32 THEN
    RAISE EXCEPTION '匿名身份密钥无效';
  END IF;

  INSERT INTO member_identity_claims (
    legacy_user_id_text,
    claim_secret_hash,
    created_at,
    updated_at
  )
  VALUES (
    clean_legacy_id,
    encode(digest(clean_claim_secret, 'sha256'), 'hex'),
    timezone('utc'::text, now()),
    timezone('utc'::text, now())
  )
  ON CONFLICT (legacy_user_id_text) DO UPDATE
  SET updated_at = timezone('utc'::text, now())
  WHERE member_identity_claims.claim_secret_hash = excluded.claim_secret_hash
  RETURNING * INTO inserted_claim;

  IF inserted_claim.legacy_user_id_text IS NULL THEN
    RAISE EXCEPTION '匿名身份已被其他密钥登记';
  END IF;

  RETURN jsonb_build_object(
    'legacy_user_id_text', inserted_claim.legacy_user_id_text,
    'updated_at', inserted_claim.updated_at
  );
END;
$$;

CREATE OR REPLACE FUNCTION get_or_create_member_profile(
  input_legacy_user_id_text TEXT DEFAULT NULL,
  input_display_name TEXT DEFAULT NULL,
  input_claim_secret TEXT DEFAULT NULL
)
RETURNS member_profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
  profile_row member_profiles%ROWTYPE;
  clean_display_name TEXT := COALESCE(NULLIF(trim(input_display_name), ''), '会员用户');
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录会员账号';
  END IF;

  INSERT INTO member_profiles (
    account_id,
    legacy_user_id_text,
    display_name,
    membership_tier,
    privacy_settings,
    notification_settings
  )
  VALUES (
    current_account,
    NULLIF(input_legacy_user_id_text, ''),
    left(clean_display_name, 80),
    'free',
    '{"hideUserId": true, "hideSensitiveItems": true, "allowPrivateShare": true}'::jsonb,
    '{"monthlySummary": true, "trendReminder": false}'::jsonb
  )
  ON CONFLICT (account_id) DO UPDATE
  SET legacy_user_id_text = COALESCE(member_profiles.legacy_user_id_text, NULLIF(input_legacy_user_id_text, '')),
      updated_at = timezone('utc'::text, now())
  RETURNING * INTO profile_row;

  IF NULLIF(input_legacy_user_id_text, '') IS NOT NULL THEN
    PERFORM link_member_identity(input_legacy_user_id_text, input_claim_secret, '当前身份');
  END IF;

  RETURN profile_row;
END;
$$;

CREATE OR REPLACE FUNCTION update_member_profile(
  input_display_name TEXT DEFAULT NULL,
  input_qq TEXT DEFAULT NULL,
  input_wechat TEXT DEFAULT NULL,
  input_contact_email TEXT DEFAULT NULL,
  input_phone TEXT DEFAULT NULL,
  input_privacy_settings JSONB DEFAULT NULL,
  input_notification_settings JSONB DEFAULT NULL
)
RETURNS member_profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
  profile_row member_profiles%ROWTYPE;
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录会员账号';
  END IF;

  UPDATE member_profiles
  SET display_name = COALESCE(NULLIF(left(trim(input_display_name), 80), ''), display_name),
      qq = NULLIF(left(trim(COALESCE(input_qq, '')), 40), ''),
      wechat = NULLIF(left(trim(COALESCE(input_wechat, '')), 80), ''),
      contact_email = NULLIF(left(trim(COALESCE(input_contact_email, '')), 160), ''),
      phone = NULLIF(left(trim(COALESCE(input_phone, '')), 40), ''),
      privacy_settings = CASE
        WHEN input_privacy_settings IS NULL THEN privacy_settings
        ELSE normalize_member_privacy_settings(input_privacy_settings)
      END,
      notification_settings = CASE
        WHEN input_notification_settings IS NULL THEN notification_settings
        ELSE normalize_member_notification_settings(input_notification_settings)
      END,
      updated_at = timezone('utc'::text, now())
  WHERE account_id = current_account
  RETURNING * INTO profile_row;

  IF profile_row.account_id IS NULL THEN
    RAISE EXCEPTION '会员资料不存在';
  END IF;

  RETURN profile_row;
END;
$$;

CREATE OR REPLACE FUNCTION register_member_device(
  input_legacy_user_id_text TEXT,
  input_claim_secret TEXT,
  input_device_label TEXT DEFAULT '当前设备',
  input_user_agent_hash TEXT DEFAULT NULL
)
RETURNS member_devices
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
  device_row member_devices%ROWTYPE;
  clean_label TEXT := COALESCE(NULLIF(left(trim(input_device_label), 40), ''), '当前设备');
  clean_hash TEXT := NULLIF(input_user_agent_hash, '');
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录会员账号';
  END IF;

  IF clean_hash IS NOT NULL AND clean_hash !~ '^[a-f0-9]{64}$' THEN
    RAISE EXCEPTION '设备指纹格式无效';
  END IF;

  PERFORM link_member_identity(input_legacy_user_id_text, input_claim_secret, clean_label);

  INSERT INTO member_devices (
    account_id,
    legacy_user_id_text,
    device_label,
    user_agent_hash,
    last_seen_at
  )
  VALUES (
    current_account,
    NULLIF(input_legacy_user_id_text, ''),
    clean_label,
    clean_hash,
    timezone('utc'::text, now())
  )
  ON CONFLICT (account_id, legacy_user_id_text, device_label) DO UPDATE
  SET user_agent_hash = excluded.user_agent_hash,
      last_seen_at = timezone('utc'::text, now())
  RETURNING * INTO device_row;

  RETURN device_row;
END;
$$;

CREATE OR REPLACE FUNCTION unlink_member_device(input_device_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
  deleted_count INTEGER;
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录会员账号';
  END IF;

  DELETE FROM member_devices
  WHERE id = input_device_id
    AND account_id = current_account;

  GET DIAGNOSTICS deleted_count = ROW_COUNT;

  IF deleted_count = 0 THEN
    RAISE EXCEPTION '设备不存在或不属于当前账号';
  END IF;

  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION require_premium_member(input_account_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  profile_tier TEXT;
BEGIN
  SELECT membership_tier INTO profile_tier
  FROM member_profiles
  WHERE account_id = input_account_id
  LIMIT 1;

  IF profile_tier NOT IN ('premium', 'lifetime') THEN
    RAISE EXCEPTION '该功能需要高级会员或永久会员';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION ensure_member_record_owner(input_account_id UUID, input_legacy_user_id_text TEXT, input_record_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
  IF input_legacy_user_id_text IS NULL OR input_legacy_user_id_text = '' THEN
    RAISE EXCEPTION '请先绑定当前匿名身份';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM member_identity_links
    WHERE account_id = input_account_id
      AND legacy_user_id_text = input_legacy_user_id_text
  ) THEN
    RAISE EXCEPTION '当前会员账号未绑定该测评身份';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM test_records
    WHERE id = input_record_id
      AND user_id_text = input_legacy_user_id_text
  ) THEN
    RAISE EXCEPTION '测评记录不存在或不属于当前身份';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION get_member_records()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录会员账号';
  END IF;

  RETURN COALESCE((
    SELECT jsonb_agg(
      jsonb_build_object(
        'id', r.id,
        'user_id_text', r.user_id_text,
        'test_type', r.test_type,
        'report_data', r.report_data,
        'created_at', r.created_at,
        'updated_at', r.updated_at,
        'details', COALESCE((
          SELECT jsonb_agg(
            jsonb_build_object(
              'record_id', tr.record_id,
              'category', tr.category,
              'item', tr.item,
              'rating', tr.rating
            )
            ORDER BY tr.category, tr.item
          )
          FROM test_results tr
          WHERE tr.record_id = r.id
        ), '[]'::jsonb)
      )
      ORDER BY r.created_at ASC
    )
    FROM test_records r
    WHERE EXISTS (
      SELECT 1
      FROM member_identity_links mil
      WHERE mil.account_id = current_account
        AND mil.legacy_user_id_text = r.user_id_text
    )
  ), '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION delete_member_record(input_record_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
  deleted_count INTEGER;
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录账号';
  END IF;

  DELETE FROM test_records r
  WHERE r.id = input_record_id
    AND EXISTS (
      SELECT 1
      FROM member_identity_links mil
      WHERE mil.account_id = current_account
        AND mil.legacy_user_id_text = r.user_id_text
    );

  GET DIAGNOSTICS deleted_count = ROW_COUNT;

  IF deleted_count = 0 THEN
    RAISE EXCEPTION '记录不存在或不属于当前账号';
  END IF;

  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION create_member_order(
  input_legacy_user_id_text TEXT,
  input_plan_code TEXT,
  input_contact_email TEXT DEFAULT NULL,
  input_contact_note TEXT DEFAULT NULL
)
RETURNS member_orders
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
  amount_value INTEGER;
  inserted_order member_orders%ROWTYPE;
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录会员账号';
  END IF;

  amount_value := CASE input_plan_code
    WHEN 'basic_monthly' THEN 1900
    WHEN 'premium_monthly' THEN 3900
    WHEN 'lifetime' THEN 29900
    ELSE NULL
  END;

  IF amount_value IS NULL THEN
    RAISE EXCEPTION '会员方案无效';
  END IF;

  INSERT INTO member_orders (
    account_id,
    legacy_user_id_text,
    plan_code,
    amount_cents,
    currency,
    status,
    provider,
    contact_email,
    contact_note
  )
  VALUES (
    current_account,
    NULLIF(input_legacy_user_id_text, ''),
    input_plan_code,
    amount_value,
    'CNY',
    'pending',
    'manual',
    NULLIF(input_contact_email, ''),
    NULLIF(input_contact_note, '')
  )
  RETURNING * INTO inserted_order;

  RETURN inserted_order;
END;
$$;

CREATE OR REPLACE FUNCTION create_member_report_unlock(
  input_legacy_user_id_text TEXT,
  input_record_id UUID,
  input_unlock_type TEXT DEFAULT 'advanced_report'
)
RETURNS member_report_unlocks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
  inserted_unlock member_report_unlocks%ROWTYPE;
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录会员账号';
  END IF;

  IF input_unlock_type NOT IN ('advanced_report', 'comparison_report', 'export_template') THEN
    RAISE EXCEPTION '解锁类型无效';
  END IF;

  PERFORM require_premium_member(current_account);
  PERFORM ensure_member_record_owner(current_account, input_legacy_user_id_text, input_record_id);

  INSERT INTO member_report_unlocks (
    account_id,
    legacy_user_id_text,
    record_id,
    unlock_type,
    source
  )
  VALUES (
    current_account,
    input_legacy_user_id_text,
    input_record_id,
    input_unlock_type,
    'membership'
  )
  ON CONFLICT (account_id, record_id, unlock_type) DO UPDATE
  SET source = excluded.source
  RETURNING * INTO inserted_unlock;

  RETURN inserted_unlock;
END;
$$;

CREATE OR REPLACE FUNCTION create_member_share_link(
  input_legacy_user_id_text TEXT,
  input_record_id UUID,
  input_title TEXT DEFAULT '我的测评报告',
  input_access_code TEXT DEFAULT NULL,
  input_hidden_sections JSONB DEFAULT '[]'::jsonb,
  input_expires_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  input_share_token TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
  inserted_link member_share_links%ROWTYPE;
  clean_access_code TEXT := NULLIF(trim(input_access_code), '');
  clean_share_token TEXT := COALESCE(NULLIF(input_share_token, ''), encode(gen_random_bytes(24), 'hex'));
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录会员账号';
  END IF;

  PERFORM require_premium_member(current_account);
  PERFORM ensure_member_record_owner(current_account, input_legacy_user_id_text, input_record_id);

  INSERT INTO member_share_links (
    share_token,
    account_id,
    legacy_user_id_text,
    record_id,
    title,
    access_code_hash,
    hidden_sections,
    expires_at,
    is_active
  )
  VALUES (
    clean_share_token,
    current_account,
    input_legacy_user_id_text,
    input_record_id,
    COALESCE(NULLIF(input_title, ''), '我的测评报告'),
    CASE WHEN clean_access_code IS NULL THEN NULL ELSE crypt(clean_access_code, gen_salt('bf')) END,
    COALESCE(input_hidden_sections, '[]'::jsonb),
    input_expires_at,
    true
  )
  RETURNING * INTO inserted_link;

  RETURN to_jsonb(inserted_link) - 'access_code_hash';
END;
$$;

CREATE OR REPLACE FUNCTION get_member_share_links()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录会员账号';
  END IF;

  RETURN COALESCE((
    SELECT jsonb_agg(
      jsonb_build_object(
        'id', id,
        'share_token', share_token,
        'account_id', account_id,
        'legacy_user_id_text', legacy_user_id_text,
        'record_id', record_id,
        'title', title,
        'hidden_sections', hidden_sections,
        'expires_at', expires_at,
        'is_active', is_active,
        'view_count', view_count,
        'created_at', created_at,
        'updated_at', updated_at
      )
      ORDER BY created_at DESC
    )
    FROM member_share_links
    WHERE account_id = current_account
  ), '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION deactivate_member_share_link(input_share_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_account UUID := auth.uid();
  updated_link member_share_links%ROWTYPE;
BEGIN
  IF current_account IS NULL THEN
    RAISE EXCEPTION '请先登录会员账号';
  END IF;

  UPDATE member_share_links
  SET is_active = false,
      updated_at = timezone('utc'::text, now())
  WHERE id = input_share_id
    AND account_id = current_account
  RETURNING * INTO updated_link;

  IF updated_link.id IS NULL THEN
    RAISE EXCEPTION '分享链接不存在或不属于当前账号';
  END IF;

  RETURN to_jsonb(updated_link) - 'access_code_hash';
END;
$$;

DROP FUNCTION IF EXISTS get_member_public_share(TEXT, TEXT);
CREATE OR REPLACE FUNCTION get_member_public_share(input_token TEXT, input_access_code TEXT DEFAULT NULL)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  link_row member_share_links%ROWTYPE;
  record_row test_records%ROWTYPE;
  detail_rows JSONB;
BEGIN
  SELECT * INTO link_row
  FROM member_share_links
  WHERE share_token = input_token
    AND is_active = true
    AND (expires_at IS NULL OR expires_at > timezone('utc'::text, now()))
  LIMIT 1;

  IF link_row.id IS NULL THEN
    RAISE EXCEPTION '分享链接不存在或已失效';
  END IF;

  IF link_row.access_code_hash IS NOT NULL
     AND (input_access_code IS NULL OR crypt(input_access_code, link_row.access_code_hash) <> link_row.access_code_hash) THEN
    RETURN jsonb_build_object(
      'requiresAccessCode', true,
      'link', jsonb_build_object('title', link_row.title, 'expires_at', link_row.expires_at)
    );
  END IF;

  SELECT * INTO record_row FROM test_records WHERE id = link_row.record_id LIMIT 1;
  IF record_row.id IS NULL THEN
    RAISE EXCEPTION '分享报告不存在';
  END IF;

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'category', category,
    'item', item,
    'rating', rating
  ) ORDER BY category, item), '[]'::jsonb)
  INTO detail_rows
  FROM test_results
  WHERE record_id = link_row.record_id;

  UPDATE member_share_links
  SET view_count = view_count + 1,
      updated_at = timezone('utc'::text, now())
  WHERE id = link_row.id;

  RETURN jsonb_build_object(
    'requiresAccessCode', false,
    'link', jsonb_build_object(
      'id', link_row.id,
      'share_token', link_row.share_token,
      'record_id', link_row.record_id,
      'title', link_row.title,
      'hidden_sections', link_row.hidden_sections,
      'expires_at', link_row.expires_at,
      'is_active', link_row.is_active,
      'view_count', link_row.view_count + 1,
      'created_at', link_row.created_at
    ),
    'record', jsonb_build_object(
      'id', record_row.id,
      'test_type', record_row.test_type,
      'report_data', record_row.report_data,
      'created_at', record_row.created_at,
      'details', detail_rows
    )
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION require_premium_member(UUID) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION ensure_member_record_owner(UUID, TEXT, UUID) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION link_member_identity(TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION register_legacy_identity_claim(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION normalize_member_username(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION reserve_member_login_name(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION get_member_login_email(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION get_member_records() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION delete_member_record(UUID) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION get_or_create_member_profile(TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION update_member_profile(TEXT, JSONB, JSONB) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION update_member_profile(TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, JSONB) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION register_member_device(TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION unlink_member_device(UUID) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION create_member_order(TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION create_member_report_unlock(TEXT, UUID, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION create_member_share_link(TEXT, UUID, TEXT, TEXT, JSONB, TIMESTAMP WITH TIME ZONE, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION get_member_share_links() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION deactivate_member_share_link(UUID) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION get_member_public_share(TEXT, TEXT) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION link_member_identity(TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION register_legacy_identity_claim(TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION reserve_member_login_name(TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION get_member_login_email(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION get_member_records() TO authenticated;
GRANT EXECUTE ON FUNCTION delete_member_record(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION get_or_create_member_profile(TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION update_member_profile(TEXT, TEXT, TEXT, TEXT, TEXT, JSONB, JSONB) TO authenticated;
GRANT EXECUTE ON FUNCTION register_member_device(TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION unlink_member_device(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION create_member_order(TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION create_member_report_unlock(TEXT, UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION create_member_share_link(TEXT, UUID, TEXT, TEXT, JSONB, TIMESTAMP WITH TIME ZONE, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION get_member_share_links() TO authenticated;
GRANT EXECUTE ON FUNCTION deactivate_member_share_link(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION get_member_public_share(TEXT, TEXT) TO anon, authenticated;

COMMENT ON TABLE member_profiles IS '会员中心资料和隐私设置';
COMMENT ON TABLE member_subscriptions IS '会员订阅状态，支付接入前可由后台手动维护';
COMMENT ON TABLE member_orders IS '会员开通和续费订单，支付接入前支持后台手动审核';
COMMENT ON TABLE member_account_events IS '会员账号事件日志';
COMMENT ON TABLE member_identity_links IS '会员账号绑定的匿名测评身份，用于跨设备读取同一账号的云端测评记录';
COMMENT ON TABLE member_identity_claims IS '匿名测评身份的本地密钥证明，只保存 sha256 hash，用于防止仅凭 user_id 绑定他人记录';
COMMENT ON TABLE member_login_names IS '会员用户名到 Supabase Auth 邮箱的映射，用于支持用户名密码登录';
COMMENT ON TABLE member_devices IS '会员账号关联设备和匿名身份绑定';
COMMENT ON TABLE member_report_unlocks IS '高级报告、对比报告、导出模板解锁记录';
COMMENT ON TABLE member_share_links IS '私密报告分享链接';


-- ============================================================================
-- 3. database/create_admin_member_session.sql
-- sha256: 6a0534145f354b05098e886ac95e71acfe63e9fcf126c4a855f0ccb3cc024433
-- ============================================================================

-- Admin session and member management RPCs
-- Run after create_admin_system.sql and database/create_member_center_tables.sql.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS admin_sessions (
  session_token_hash TEXT PRIMARY KEY,
  admin_id UUID NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('super_admin', 'admin', 'moderator')),
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_admin_sessions_admin_id ON admin_sessions(admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_expires_at ON admin_sessions(expires_at);

ALTER TABLE admin_sessions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS admin_login_attempts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  username TEXT NOT NULL,
  success BOOLEAN NOT NULL DEFAULT false,
  attempted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_admin_login_attempts_username_time ON admin_login_attempts(username, attempted_at DESC);

ALTER TABLE admin_login_attempts ENABLE ROW LEVEL SECURITY;

ALTER TABLE message_replies
ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT false;

DROP FUNCTION IF EXISTS verify_admin_password(TEXT);
CREATE OR REPLACE FUNCTION verify_admin_password(input_password TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
  RETURN jsonb_build_object(
    'is_valid',
    EXISTS (
      SELECT 1
      FROM admins
      WHERE is_active = true
        AND password_hash IS NOT NULL
        AND crypt(input_password, password_hash) = password_hash
    )
  );
END;
$$;

DROP FUNCTION IF EXISTS change_admin_password(TEXT, TEXT, TEXT);
CREATE OR REPLACE FUNCTION change_admin_password(input_session_token_hash TEXT, current_password TEXT, new_password TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  admin_row admins%ROWTYPE;
BEGIN
  SELECT a.* INTO admin_row
  FROM admins a
  JOIN admin_sessions s ON s.admin_id = a.id
  WHERE s.session_token_hash = input_session_token_hash
    AND s.expires_at > timezone('utc'::text, now())
    AND a.is_active = true
  LIMIT 1;

  IF admin_row.id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', '管理员会话无效或已过期');
  END IF;

  IF crypt(current_password, admin_row.password_hash) <> admin_row.password_hash THEN
    RETURN jsonb_build_object('success', false, 'error', '当前密码错误');
  END IF;

  IF length(COALESCE(new_password, '')) < 8 THEN
    RETURN jsonb_build_object('success', false, 'error', '新密码至少8位');
  END IF;

  UPDATE admins
  SET password_hash = crypt(new_password, gen_salt('bf')),
      updated_at = timezone('utc'::text, now())
  WHERE id = admin_row.id;

  DELETE FROM admin_sessions WHERE admin_id = admin_row.id;

  RETURN jsonb_build_object('success', true);
END;
$$;

CREATE OR REPLACE FUNCTION create_admin_session(
  input_username TEXT,
  input_password TEXT,
  input_session_token_hash TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  admin_row admins%ROWTYPE;
  clean_username TEXT := lower(trim(COALESCE(input_username, '')));
  failed_count INTEGER;
BEGIN
  IF clean_username = ''
    OR COALESCE(input_password, '') = ''
    OR input_session_token_hash IS NULL
    OR input_session_token_hash !~ '^[a-f0-9]{64}$'
  THEN
    RAISE EXCEPTION '用户名或密码错误';
  END IF;

  DELETE FROM admin_login_attempts
  WHERE attempted_at < timezone('utc'::text, now()) - interval '1 day';

  SELECT count(*) INTO failed_count
  FROM admin_login_attempts
  WHERE username = clean_username
    AND success = false
    AND attempted_at > timezone('utc'::text, now()) - interval '15 minutes';

  IF failed_count >= 8 THEN
    RAISE EXCEPTION '登录尝试过多，请15分钟后再试';
  END IF;

  SELECT * INTO admin_row
  FROM admins
  WHERE lower(username) = clean_username AND is_active = true
  LIMIT 1;

  IF admin_row.id IS NULL THEN
    INSERT INTO admin_login_attempts (username, success) VALUES (clean_username, false);
    RAISE EXCEPTION '用户名或密码错误';
  END IF;

  IF admin_row.password_hash IS NULL OR crypt(input_password, admin_row.password_hash) <> admin_row.password_hash THEN
    INSERT INTO admin_login_attempts (username, success) VALUES (clean_username, false);
    RAISE EXCEPTION '用户名或密码错误';
  END IF;

  DELETE FROM admin_login_attempts WHERE username = clean_username;
  DELETE FROM admin_sessions WHERE expires_at <= timezone('utc'::text, now());

  INSERT INTO admin_sessions (session_token_hash, admin_id, role, expires_at)
  VALUES (input_session_token_hash, admin_row.id, admin_row.role, timezone('utc'::text, now()) + interval '8 hours')
  ON CONFLICT (session_token_hash) DO UPDATE
  SET admin_id = excluded.admin_id,
      role = excluded.role,
      expires_at = excluded.expires_at;

  UPDATE admins SET last_login = timezone('utc'::text, now()) WHERE id = admin_row.id;

  RETURN jsonb_build_object(
    'id', admin_row.id,
    'username', admin_row.username,
    'role', admin_row.role,
    'expires_at', timezone('utc'::text, now()) + interval '8 hours'
  );
END;
$$;

CREATE OR REPLACE FUNCTION get_admin_session(input_session_token_hash TEXT)
RETURNS TABLE(admin_id UUID, username TEXT, role TEXT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
BEGIN
  RETURN QUERY
  SELECT a.id, a.username, s.role
  FROM admin_sessions s
  JOIN admins a ON a.id = s.admin_id
  WHERE s.session_token_hash = input_session_token_hash
    AND s.expires_at > timezone('utc'::text, now())
    AND a.is_active = true
  LIMIT 1;
END;
$$;

CREATE OR REPLACE FUNCTION require_admin(input_session_token_hash TEXT)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  current_admin UUID;
BEGIN
  SELECT admin_id INTO current_admin FROM get_admin_session(input_session_token_hash) LIMIT 1;
  IF current_admin IS NULL THEN
    RAISE EXCEPTION '管理员会话无效或已过期';
  END IF;
  RETURN current_admin;
END;
$$;

CREATE OR REPLACE FUNCTION member_admin_overview(input_session_token_hash TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  ignored UUID;
BEGIN
  ignored := require_admin(input_session_token_hash);
  RETURN jsonb_build_object(
    'totalMembers', (SELECT count(*) FROM member_profiles),
    'activeSubscriptions', (SELECT count(*) FROM member_subscriptions WHERE status IN ('active', 'trialing')),
    'pendingOrders', (SELECT count(*) FROM member_orders WHERE status = 'pending'),
    'activeShares', (SELECT count(*) FROM member_share_links WHERE is_active = true)
  );
END;
$$;

CREATE OR REPLACE FUNCTION member_admin_orders(input_session_token_hash TEXT, input_limit INTEGER DEFAULT 50)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  ignored UUID;
BEGIN
  ignored := require_admin(input_session_token_hash);
  RETURN COALESCE((
    SELECT jsonb_agg(to_jsonb(o) ORDER BY o.created_at DESC)
    FROM (SELECT * FROM member_orders ORDER BY created_at DESC LIMIT input_limit) o
  ), '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION member_admin_members(input_session_token_hash TEXT, input_limit INTEGER DEFAULT 50, input_offset INTEGER DEFAULT 0)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  ignored UUID;
BEGIN
  ignored := require_admin(input_session_token_hash);
  RETURN jsonb_build_object(
    'total', (SELECT count(*) FROM member_profiles),
    'members', COALESCE((
      SELECT jsonb_agg(
        to_jsonb(p) ||
        jsonb_build_object(
          'subscription', (
            SELECT to_jsonb(s)
            FROM member_subscriptions s
            WHERE s.account_id = p.account_id
            ORDER BY s.created_at DESC
            LIMIT 1
          ),
          'orders', COALESCE((
            SELECT jsonb_agg(to_jsonb(o) ORDER BY o.created_at DESC)
            FROM member_orders o
            WHERE o.account_id = p.account_id
          ), '[]'::jsonb)
        )
      )
      FROM (
        SELECT *
        FROM member_profiles
        ORDER BY created_at DESC
        LIMIT input_limit
        OFFSET input_offset
      ) p
    ), '[]'::jsonb)
  );
END;
$$;

CREATE OR REPLACE FUNCTION apply_member_order_approval(
  input_order_id UUID,
  input_provider TEXT DEFAULT NULL,
  input_provider_ref TEXT DEFAULT NULL,
  input_admin_note TEXT DEFAULT '订单已开通',
  input_event_type TEXT DEFAULT 'member_order_approved'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  order_row member_orders%ROWTYPE;
  next_tier TEXT;
  next_ends_at TIMESTAMP WITH TIME ZONE;
  resolved_provider TEXT;
  resolved_provider_ref TEXT;
  was_already_approved BOOLEAN;
BEGIN
  SELECT * INTO order_row FROM member_orders WHERE id = input_order_id FOR UPDATE;
  IF order_row.id IS NULL THEN
    RAISE EXCEPTION '订单不存在';
  END IF;

  IF order_row.status IN ('canceled', 'refunded') THEN
    RAISE EXCEPTION '订单已取消或退款，不能审核通过';
  END IF;
  was_already_approved := order_row.status = 'approved';
  resolved_provider := COALESCE(NULLIF(input_provider, ''), order_row.provider, 'manual');
  resolved_provider_ref := COALESCE(NULLIF(input_provider_ref, ''), order_row.provider_ref, order_row.id::TEXT);

  next_tier := CASE order_row.plan_code
    WHEN 'basic_monthly' THEN 'basic'
    WHEN 'premium_monthly' THEN 'premium'
    WHEN 'lifetime' THEN 'lifetime'
    ELSE 'premium'
  END;
  next_ends_at := CASE WHEN order_row.plan_code = 'lifetime' THEN NULL ELSE timezone('utc'::text, now()) + interval '31 days' END;

  UPDATE member_orders
  SET status = 'approved',
      provider = resolved_provider,
      provider_ref = resolved_provider_ref,
      paid_at = COALESCE(paid_at, timezone('utc'::text, now())),
      reviewed_at = timezone('utc'::text, now()),
      admin_note = COALESCE(NULLIF(input_admin_note, ''), admin_note, '订单已开通')
  WHERE id = input_order_id;

  UPDATE member_profiles
  SET membership_tier = next_tier,
      updated_at = timezone('utc'::text, now())
  WHERE account_id = order_row.account_id;

  INSERT INTO member_subscriptions (account_id, plan_code, status, provider, provider_ref, starts_at, ends_at)
  VALUES (order_row.account_id, order_row.plan_code, 'active', resolved_provider, resolved_provider_ref, timezone('utc'::text, now()), next_ends_at)
  ON CONFLICT (provider, provider_ref) WHERE provider_ref IS NOT NULL DO UPDATE
  SET account_id = excluded.account_id,
      plan_code = excluded.plan_code,
      status = 'active',
      starts_at = member_subscriptions.starts_at,
      ends_at = excluded.ends_at,
      updated_at = timezone('utc'::text, now());

  IF NOT was_already_approved THEN
    INSERT INTO member_account_events (account_id, legacy_user_id_text, event_type, event_payload)
    VALUES (
      order_row.account_id,
      order_row.legacy_user_id_text,
      COALESCE(NULLIF(input_event_type, ''), 'member_order_approved'),
      jsonb_build_object(
        'order_id', order_row.id,
        'plan_code', order_row.plan_code,
        'tier', next_tier,
        'provider', resolved_provider,
        'provider_ref', resolved_provider_ref
      )
    );
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'order_id', order_row.id,
    'tier', next_tier,
    'idempotent', was_already_approved,
    'provider', resolved_provider,
    'provider_ref', resolved_provider_ref
  );
END;
$$;

CREATE OR REPLACE FUNCTION member_admin_approve_order(input_session_token_hash TEXT, input_order_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  ignored UUID;
  approval_result JSONB;
BEGIN
  ignored := require_admin(input_session_token_hash);
  approval_result := apply_member_order_approval(
    input_order_id,
    'manual',
    input_order_id::TEXT,
    '后台手动审核通过',
    'admin_order_approved'
  );
  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION member_admin_reject_order(input_session_token_hash TEXT, input_order_id UUID, input_note TEXT DEFAULT '后台手动拒绝')
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  ignored UUID;
  order_row member_orders%ROWTYPE;
BEGIN
  ignored := require_admin(input_session_token_hash);
  SELECT * INTO order_row FROM member_orders WHERE id = input_order_id FOR UPDATE;
  IF order_row.id IS NULL THEN
    RAISE EXCEPTION '订单不存在';
  END IF;
  IF order_row.status = 'approved' THEN
    RAISE EXCEPTION '订单已开通，不能拒绝';
  END IF;

  UPDATE member_orders
  SET status = 'rejected',
      reviewed_at = timezone('utc'::text, now()),
      admin_note = input_note
  WHERE id = input_order_id;

  INSERT INTO member_account_events (account_id, legacy_user_id_text, event_type, event_payload)
  VALUES (
    order_row.account_id,
    order_row.legacy_user_id_text,
    'admin_order_rejected',
    jsonb_build_object('order_id', order_row.id, 'note', input_note)
  );

  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION admin_delete_message(input_session_token_hash TEXT, input_message_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  ignored UUID;
BEGIN
  ignored := require_admin(input_session_token_hash);
  DELETE FROM messages WHERE id = input_message_id;
  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION admin_create_message(input_session_token_hash TEXT, input_text TEXT, input_original_text TEXT)
RETURNS messages
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  ignored UUID;
  inserted_message messages%ROWTYPE;
  clean_text TEXT := left(trim(COALESCE(input_text, '')), 200);
  clean_original_text TEXT := left(trim(COALESCE(input_original_text, input_text, '')), 200);
BEGIN
  ignored := require_admin(input_session_token_hash);

  IF clean_text = '' THEN
    RAISE EXCEPTION '留言内容不能为空';
  END IF;

  INSERT INTO messages (user_id, text, original_text, created_at)
  VALUES ('admin', clean_text, clean_original_text, timezone('utc'::text, now()))
  RETURNING * INTO inserted_message;

  RETURN inserted_message;
END;
$$;

CREATE OR REPLACE FUNCTION admin_create_reply(
  input_session_token_hash TEXT,
  input_message_id UUID,
  input_text TEXT,
  input_original_text TEXT
)
RETURNS message_replies
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  ignored UUID;
  inserted_reply message_replies%ROWTYPE;
  clean_text TEXT := left(trim(COALESCE(input_text, '')), 200);
  clean_original_text TEXT := left(trim(COALESCE(input_original_text, input_text, '')), 200);
BEGIN
  ignored := require_admin(input_session_token_hash);

  IF clean_text = '' THEN
    RAISE EXCEPTION '回复内容不能为空';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM messages WHERE id = input_message_id) THEN
    RAISE EXCEPTION '消息不存在';
  END IF;

  INSERT INTO message_replies (message_id, user_id, text, original_text, is_admin, created_at)
  VALUES (input_message_id, 'admin', clean_text, clean_original_text, true, timezone('utc'::text, now()))
  RETURNING * INTO inserted_reply;

  RETURN inserted_reply;
END;
$$;

CREATE OR REPLACE FUNCTION admin_delete_reply(input_session_token_hash TEXT, input_reply_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  ignored UUID;
BEGIN
  ignored := require_admin(input_session_token_hash);
  DELETE FROM message_replies WHERE id = input_reply_id;
  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION admin_toggle_message_pin(input_session_token_hash TEXT, input_message_id UUID, input_is_pinned BOOLEAN)
RETURNS messages
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  ignored UUID;
  updated_message messages%ROWTYPE;
BEGIN
  ignored := require_admin(input_session_token_hash);

  UPDATE messages
  SET is_pinned = COALESCE(input_is_pinned, false)
  WHERE id = input_message_id
  RETURNING * INTO updated_message;

  IF updated_message.id IS NULL THEN
    RAISE EXCEPTION '消息不存在';
  END IF;

  RETURN updated_message;
END;
$$;

CREATE OR REPLACE FUNCTION admin_update_message_reaction_count(
  input_session_token_hash TEXT,
  input_message_id UUID,
  input_reaction_type TEXT,
  input_count INTEGER
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  ignored UUID;
  target_is_like BOOLEAN;
BEGIN
  ignored := require_admin(input_session_token_hash);

  IF input_reaction_type NOT IN ('likes', 'dislikes') THEN
    RAISE EXCEPTION '反应类型无效';
  END IF;

  IF input_count IS NULL OR input_count < 0 OR input_count > 10000 THEN
    RAISE EXCEPTION '反应数量无效';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM messages WHERE id = input_message_id) THEN
    RAISE EXCEPTION '消息不存在';
  END IF;

  target_is_like := input_reaction_type = 'likes';

  DELETE FROM message_reactions
  WHERE message_id = input_message_id
    AND is_like = target_is_like;

  INSERT INTO message_reactions (message_id, user_id, is_like)
  SELECT input_message_id, 'admin_adjust_' || input_reaction_type || '_' || gs::TEXT, target_is_like
  FROM generate_series(1, input_count) AS gs;

  RETURN true;
END;
$$;

REVOKE EXECUTE ON FUNCTION verify_admin_password(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION change_admin_password(TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION get_admin_session(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION require_admin(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION apply_member_order_approval(UUID, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION create_admin_session(TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION member_admin_overview(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION member_admin_members(TEXT, INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION member_admin_orders(TEXT, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION member_admin_approve_order(TEXT, UUID) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION member_admin_reject_order(TEXT, UUID, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION admin_create_message(TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION admin_create_reply(TEXT, UUID, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION admin_delete_message(TEXT, UUID) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION admin_delete_reply(TEXT, UUID) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION admin_toggle_message_pin(TEXT, UUID, BOOLEAN) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION admin_update_message_reaction_count(TEXT, UUID, TEXT, INTEGER) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION create_admin_session(TEXT, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION change_admin_password(TEXT, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION apply_member_order_approval(UUID, TEXT, TEXT, TEXT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION member_admin_overview(TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION member_admin_members(TEXT, INTEGER, INTEGER) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION member_admin_orders(TEXT, INTEGER) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION member_admin_approve_order(TEXT, UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION member_admin_reject_order(TEXT, UUID, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION admin_create_message(TEXT, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION admin_create_reply(TEXT, UUID, TEXT, TEXT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION admin_delete_message(TEXT, UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION admin_delete_reply(TEXT, UUID) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION admin_toggle_message_pin(TEXT, UUID, BOOLEAN) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION admin_update_message_reaction_count(TEXT, UUID, TEXT, INTEGER) TO anon, authenticated;

COMMENT ON TABLE admin_sessions IS '后台管理员短期会话，前端只保存明文 token，数据库只保存 hash';
COMMENT ON TABLE admin_login_attempts IS '后台登录失败计数，用于数据库侧限速';


-- ============================================================================
-- 4. database/member_center_deployment_check.sql
-- sha256: 3d1a919c14f420d0946a1adabe5a37d20403827dce736c50a3e8e762ac195650
-- ============================================================================

-- Member center deployment check
-- Run after create_member_center_tables.sql and create_admin_member_session.sql.

WITH required_relations(name) AS (
  VALUES
    ('member_profiles'),
    ('member_subscriptions'),
    ('member_orders'),
    ('member_account_events'),
    ('member_identity_links'),
    ('member_identity_claims'),
    ('member_login_names'),
    ('member_devices'),
    ('member_report_unlocks'),
    ('member_share_links'),
    ('admin_sessions'),
    ('admin_login_attempts')
),
required_functions(name) AS (
  VALUES
    ('get_or_create_member_profile'),
    ('link_member_identity'),
    ('register_legacy_identity_claim'),
    ('normalize_member_auth_user_metadata'),
    ('create_user_settings'),
    ('handle_new_user'),
    ('reserve_member_login_name'),
    ('get_member_login_email'),
    ('get_member_records'),
    ('delete_member_record'),
    ('update_member_profile'),
    ('register_member_device'),
    ('unlink_member_device'),
    ('create_member_order'),
    ('create_member_report_unlock'),
    ('create_member_share_link'),
    ('get_member_share_links'),
    ('deactivate_member_share_link'),
    ('get_member_public_share'),
    ('create_admin_session'),
    ('change_admin_password'),
    ('get_admin_session'),
    ('require_admin'),
    ('apply_member_order_approval'),
    ('member_admin_overview'),
    ('member_admin_members'),
    ('member_admin_orders'),
    ('member_admin_approve_order'),
    ('member_admin_reject_order'),
    ('admin_create_message'),
    ('admin_create_reply'),
    ('admin_delete_message'),
    ('admin_delete_reply'),
    ('admin_toggle_message_pin'),
    ('admin_update_message_reaction_count')
),
relation_check AS (
  SELECT
    name,
    EXISTS (
      SELECT 1
      FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = name
    ) AS ok
  FROM required_relations
),
function_check AS (
  SELECT
    name,
    EXISTS (
      SELECT 1
      FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public' AND p.proname = name
    ) AS ok
  FROM required_functions
),
rls_check AS (
  SELECT
    c.relname AS name,
    c.relrowsecurity AS ok
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname IN (
      'member_profiles',
      'member_subscriptions',
      'member_orders',
      'member_account_events',
      'member_identity_links',
      'member_identity_claims',
      'member_login_names',
      'member_devices',
      'member_report_unlocks',
      'member_share_links',
      'admin_sessions',
      'admin_login_attempts'
    )
),
security_policy_check AS (
  SELECT
    'old_link_member_identity_signature_removed' AS name,
    to_regprocedure('public.link_member_identity(text, text)') IS NULL AS ok
  UNION ALL
  SELECT
    'old_get_or_create_member_profile_signature_removed' AS name,
    to_regprocedure('public.get_or_create_member_profile(text, text)') IS NULL AS ok
  UNION ALL
  SELECT
    'old_register_member_device_signature_removed' AS name,
    to_regprocedure('public.register_member_device(text, text, text)') IS NULL AS ok
  UNION ALL
  SELECT
    'member_identity_claims_no_read_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_identity_claims'
        AND policyname = 'member_identity_claims_no_read'
    ) AS ok
  UNION ALL
  SELECT
    'member_identity_claims_not_selectable' AS name,
    NOT has_table_privilege('authenticated', 'member_identity_claims', 'SELECT')
      AND NOT has_table_privilege('anon', 'member_identity_claims', 'SELECT') AS ok
  UNION ALL
  SELECT
    'member_login_names_not_selectable' AS name,
    NOT has_table_privilege('authenticated', 'member_login_names', 'SELECT')
      AND NOT has_table_privilege('anon', 'member_login_names', 'SELECT') AS ok
  UNION ALL
  SELECT
    'auth_user_metadata_normalizer_trigger_exists' AS name,
    EXISTS (
      SELECT 1
      FROM pg_trigger trigger_row
      JOIN pg_class relation_row ON relation_row.oid = trigger_row.tgrelid
      JOIN pg_namespace namespace_row ON namespace_row.oid = relation_row.relnamespace
      WHERE namespace_row.nspname = 'auth'
        AND relation_row.relname = 'users'
        AND trigger_row.tgname = 'aaa_member_auth_user_metadata_before_write'
        AND NOT trigger_row.tgisinternal
    ) AS ok
  UNION ALL
  SELECT
    'legacy_handle_new_user_no_new_username' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_proc proc_row
      JOIN pg_namespace namespace_row ON namespace_row.oid = proc_row.pronamespace
      WHERE namespace_row.nspname = 'public'
        AND proc_row.proname = 'handle_new_user'
        AND pg_get_functiondef(proc_row.oid) ILIKE '%new.username%'
    ) AS ok
  UNION ALL
  SELECT
    'legacy_create_user_settings_sets_required_defaults' AS name,
    EXISTS (
      SELECT 1
      FROM pg_proc proc_row
      JOIN pg_namespace namespace_row ON namespace_row.oid = proc_row.pronamespace
      WHERE namespace_row.nspname = 'public'
        AND proc_row.proname = 'create_user_settings'
        AND pg_get_functiondef(proc_row.oid) ILIKE '%privacy_level%'
        AND pg_get_functiondef(proc_row.oid) ILIKE '%theme%'
        AND pg_get_functiondef(proc_row.oid) ILIKE '%COALESCE(NULLIF(trim(p_display_name)%'
    ) AS ok
  UNION ALL
  SELECT
    'member_identity_links_no_owner_insert_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_identity_links'
        AND policyname = 'member_identity_links_owner_insert'
    ) AS ok
  UNION ALL
  SELECT
    'member_identity_links_no_owner_update_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_identity_links'
        AND policyname = 'member_identity_links_owner_update'
    ) AS ok
  UNION ALL
  SELECT
    'member_identity_links_no_owner_delete_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_identity_links'
        AND policyname = 'member_identity_links_owner_delete'
    ) AS ok
  UNION ALL
  SELECT
    'member_identity_links_write_not_granted' AS name,
    NOT has_table_privilege('authenticated', 'member_identity_links', 'INSERT')
      AND NOT has_table_privilege('authenticated', 'member_identity_links', 'UPDATE')
      AND NOT has_table_privilege('authenticated', 'member_identity_links', 'DELETE') AS ok
  UNION ALL
  SELECT
    'member_profiles_no_owner_insert_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_profiles'
        AND policyname = 'member_profiles_owner_insert'
    ) AS ok
  UNION ALL
  SELECT
    'member_profiles_no_owner_update_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_profiles'
        AND policyname = 'member_profiles_owner_update'
    ) AS ok
  UNION ALL
  SELECT
    'member_share_links_no_public_select_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_share_links'
        AND policyname = 'member_share_links_public_read_active'
    ) AS ok
  UNION ALL
  SELECT
    'member_devices_no_owner_insert_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_devices'
        AND policyname = 'member_devices_owner_insert'
    ) AS ok
  UNION ALL
  SELECT
    'member_account_events_no_owner_insert_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_account_events'
        AND policyname = 'member_account_events_owner_insert'
    ) AS ok
  UNION ALL
  SELECT
    'member_devices_no_owner_update_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_devices'
        AND policyname = 'member_devices_owner_update'
    ) AS ok
  UNION ALL
  SELECT
    'member_devices_delete_not_granted' AS name,
    NOT has_table_privilege('authenticated', 'member_devices', 'DELETE') AS ok
  UNION ALL
  SELECT
    'member_share_links_no_owner_read_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_share_links'
        AND policyname = 'member_share_links_owner_read'
    ) AS ok
  UNION ALL
  SELECT
    'member_orders_no_owner_insert_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_orders'
        AND policyname = 'member_orders_owner_insert'
    ) AS ok
  UNION ALL
  SELECT
    'member_report_unlocks_no_owner_insert_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_report_unlocks'
        AND policyname = 'member_report_unlocks_owner_insert'
    ) AS ok
  UNION ALL
  SELECT
    'member_share_links_no_owner_insert_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_share_links'
        AND policyname = 'member_share_links_owner_insert'
    ) AS ok
  UNION ALL
  SELECT
    'member_share_links_no_owner_update_policy' AS name,
    NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = 'member_share_links'
        AND policyname = 'member_share_links_owner_update'
    ) AS ok
  UNION ALL
  SELECT
    'member_share_links_hash_not_selectable_by_authenticated' AS name,
    NOT has_column_privilege('authenticated', 'member_share_links', 'access_code_hash', 'SELECT') AS ok
  UNION ALL
  SELECT
    'member_share_links_hash_not_selectable_by_anon' AS name,
    NOT has_column_privilege('anon', 'member_share_links', 'access_code_hash', 'SELECT') AS ok
  UNION ALL
  SELECT
    'delete_member_record_not_executable_by_anon' AS name,
    NOT has_function_privilege('anon', 'delete_member_record(uuid)', 'EXECUTE') AS ok
  UNION ALL
  SELECT
    'verify_admin_password_not_executable_by_anon' AS name,
    NOT has_function_privilege('anon', 'verify_admin_password(text)', 'EXECUTE') AS ok
  UNION ALL
  SELECT
    'get_admin_session_not_executable_by_anon' AS name,
    NOT has_function_privilege('anon', 'get_admin_session(text)', 'EXECUTE') AS ok
  UNION ALL
  SELECT
    'require_admin_not_executable_by_anon' AS name,
    NOT has_function_privilege('anon', 'require_admin(text)', 'EXECUTE') AS ok
  UNION ALL
  SELECT
    'apply_member_order_approval_not_executable_by_anon' AS name,
    NOT has_function_privilege('anon', 'apply_member_order_approval(uuid, text, text, text, text)', 'EXECUTE') AS ok
  UNION ALL
  SELECT
    'admin_message_delete_rpc_exists' AS name,
    has_function_privilege('anon', 'admin_delete_message(text, uuid)', 'EXECUTE') AS ok
  UNION ALL
  SELECT
    'admin_message_create_rpc_exists' AS name,
    has_function_privilege('anon', 'admin_create_message(text, text, text)', 'EXECUTE') AS ok
  UNION ALL
  SELECT
    'admin_message_pin_rpc_exists' AS name,
    has_function_privilege('anon', 'admin_toggle_message_pin(text, uuid, boolean)', 'EXECUTE') AS ok
  UNION ALL
  SELECT
    'admin_login_attempts_rls_enabled' AS name,
    COALESCE((
      SELECT c.relrowsecurity
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public' AND c.relname = 'admin_login_attempts'
    ), false) AS ok
  UNION ALL
  SELECT
    'member_subscriptions_provider_ref_unique_index' AS name,
    EXISTS (
      SELECT 1
      FROM pg_indexes
      WHERE schemaname = 'public'
        AND tablename = 'member_subscriptions'
        AND indexname = 'idx_member_subscriptions_provider_ref_unique'
    ) AS ok
  UNION ALL
  SELECT
    'member_orders_provider_ref_unique_index' AS name,
    EXISTS (
      SELECT 1
      FROM pg_indexes
      WHERE schemaname = 'public'
        AND tablename = 'member_orders'
        AND indexname = 'idx_member_orders_provider_ref_unique'
    ) AS ok
)
SELECT 'table' AS check_type, name, ok FROM relation_check
UNION ALL
SELECT 'function' AS check_type, name, ok FROM function_check
UNION ALL
SELECT 'rls' AS check_type, name, ok FROM rls_check
UNION ALL
SELECT 'security' AS check_type, name, ok FROM security_policy_check
ORDER BY check_type, name;
